build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
args: {}
labels:
  org.opencontainers.image.title: "Firefly III AI Categorizer"
  org.opencontainers.image.source: "https://github.com/ejagombar/FireflyIII-AI-Categorizer"
